version: '3.7'
services:
  gpload:
    container_name: gpload
    env_file:
      - .env
    build:
      args:
        BIN_FILE: greenplum-loaders-5.17.0-rhel7-x86_64.zip
      context: .
      dockerfile: dockerfile
    command: bash -c ". greenplum_loaders_path.sh && gpload -l /log/log_.txt -f extract_config.yml"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./extract_config.yml:/build/extract_config.yml
      - ./log:/log
