---
VERSION: 1.0.0.1
GPLOAD:
  INPUT:
    - SOURCE:
        FILE:
          - /data/input.csv
    - COLUMNS:
        - one: float4
        - two: text
    - FORMAT: csv
    - ERROR_LIMIT: 25
    - LOG_ERRORS: true
  OUTPUT:
    - TABLE: public.table_name
    - MODE: INSERT


