---
VERSION: 1.0.0.1
GPLOAD:
  INPUT:
    - SOURCE:
        FILE:
          - /data/input.txt
    - COLUMNS:
        - one: text
        - two: float4
    - FORMAT: text
    - ERROR_LIMIT: 25
    - LOG_ERRORS: true
  OUTPUT:
    - TABLE: ws_mkt_ops.js_test
    - MODE: INSERT

