---
VERSION: 1.0.0.1
GPLOAD:
  INPUT:
    - SOURCE:
        FILE:
          - /data/input.csv
    - COLUMNS:
        - one: text
        - two: float4
    - FORMAT: csv
    - ERROR_LIMIT: 25
    - LOG_ERRORS: true
  OUTPUT:
    - TABLE: test.table_name2
    - MODE: INSERT

